version: '2'
services:
  nginx:
    container_name: nginx-ingress
    image: chengxiuluo/nginx:latest
    ports:
      - "80:80"
    links:
      - frontend1
      - frontend2
      - frontend3
      - backend1
      - backend2
      - backend3

  frontend1:
    container_name: frontend1
    image: chengxiuluo/todolist-frontend:latest
  frontend2:
    container_name: frontend2
    image: chengxiuluo/todolist-frontend:latest
  frontend3:
    container_name: frontend3
    image: chengxiuluo/todolist-frontend:latest


  mysql:
    container_name: db
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=TodoList
    volumes:
      - .:/data
    ports:
      - "3306:3306"

  backend1:
    container_name: backend1
    image: chengxiuluo/todolist-backend:latest
    links:
      - mysql:mysql_machine
  backend2:
    container_name: backend2
    image: chengxiuluo/todolist-backend:latest
    links:
      - mysql:mysql_machine
  backend3:
    container_name: backend3
    image: chengxiuluo/todolist-backend:latest
    links:
      - mysql:mysql_machine
